name: PUSH Image to DOCKER HUB
on: 
    push:
        branches:
            - "*"

jobs:
    hub_push:
        name: Pushing the Docker image to the Docker Hub
        runs-on: ubuntu-latest

        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              run: |
                docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - name: Build Docker Image
              run: |
                docker build --tag test_container .
            - name: Push to Hub
              run: |
                docker tag test_container ${{ secrets.DOCKER_USERNAME }}/test_container
                docker push ${{ secrets.DOCKER_USERNAME }}/test_container




